ZSH_THEME="bira"

plugins=(common-aliases tmux mercurial zsh-autosuggestions)

# User configuration

setopt append_history
setopt inc_append_history
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_find_no_dups
setopt always_to_end
setopt extended_glob
setopt glob_complete

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

autoload -U edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

export HISTFILE=~/.zsh_history  # ensure history file visibility
export HH_CONFIG=hicolor        # get more colors
export REPORTTIME=30
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=green'
export EDITOR=vim

export RPROMPT=''
